# Generated by Django 5.2.15 on 2026-06-09 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_product_effective_date_importfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Product Code')),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
                ('specification', models.CharField(blank=True, max_length=200, verbose_name='Specification')),
                ('approval', models.CharField(blank=True, max_length=200, verbose_name='Approval')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pricing_records', to='core.masterproduct'),
        ),
    ]
