# Generated by Django 5.2.15 on 2026-06-09 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_masterproduct_product_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterproduct',
            name='packaging',
            field=models.CharField(blank=True, max_length=100, verbose_name='Packaging'),
        ),
    ]
