# Generated by Django 5.2.15 on 2026-06-10 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_quotation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_cost_per_liter', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Production Cost Per Liter')),
                ('production_cost_date', models.DateTimeField(auto_now=True, verbose_name='Production Cost Date')),
                ('final_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Final Cost')),
                ('selling_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Selling Price')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Quantity')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Price')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Discount')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricings', to='core.masterproduct', verbose_name='Product')),
            ],
        ),
    ]
