# Generated by Django 5.2.15 on 2026-06-10 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_pricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='packaging',
            field=models.CharField(blank=True, max_length=100, verbose_name='Packaging'),
        ),
    ]
