# Generated by Django 5.2.15 on 2026-06-11 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_notification'),
        ('core', '0007_pricing_packaging'),
    ]

    operations = [
    ]