# Generated by Django 5.2.15 on 2026-06-11 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_merge_0006_notification_0007_pricing_packaging'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=255, verbose_name='Contact Name')),
                ('opportunity_name', models.CharField(max_length=255, verbose_name='Opportunity Name')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Contact Email')),
                ('contact_phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Contact Phone')),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Revenue (AED)')),
                ('stage', models.CharField(choices=[('New', 'New'), ('Qualified', 'Qualified'), ('Proposition', 'Proposition'), ('Won', 'Won')], default='New', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('salesperson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
