# Generated by Django 5.2.15 on 2026-06-12 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterproduct',
            name='liters_per_case',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Liters per case'),
        ),
        migrations.AddField(
            model_name='masterproduct',
            name='viscosity',
            field=models.CharField(blank=True, max_length=100, verbose_name='Viscosity'),
        ),
    ]
