# Generated by Django 6.0.6 on 2026-06-22 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_masterproduct_liters_per_case_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterproduct',
            name='approval',
            field=models.CharField(blank=True, max_length=500, verbose_name='Approval'),
        ),
        migrations.AlterField(
            model_name='masterproduct',
            name='description',
            field=models.CharField(max_length=500, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='masterproduct',
            name='specification',
            field=models.CharField(blank=True, max_length=500, verbose_name='Specification'),
        ),
    ]
