# Generated by Django 6.0.6 on 2026-06-23 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_masterproduct_approval_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterproduct',
            name='code',
            field=models.CharField(max_length=50, verbose_name='Product Code'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(max_length=50),
        ),
    ]
