# Generated by Django 6.0.6 on 2026-06-25 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_masterproduct_code_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterproduct',
            name='code',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Product Code'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
