# Generated by Django 6.0.6 on 2026-06-25 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_masterproduct_code_alter_product_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='core.product'),
        ),
        migrations.AddField(
            model_name='lead',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='lead',
            name='won_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
